# Generated by Django 4.2.5 on 2024-03-14 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='presenter',
            new_name='organizer',
        ),
        migrations.RemoveField(
            model_name='event',
            name='follower_count',
        ),
    ]
