# Generated by Django 4.2.5 on 2024-03-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
