# Generated by Django 4.2.5 on 2024-03-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_event_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('paid', 'Paid'), ('free', 'Free')], default='free', max_length=4),
        ),
    ]
