# Generated by Django 4.2.5 on 2024-03-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_event_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
